# Rakefile
require 'opal'
desc "Build our app to build.js"
task :build do
  Opal::Processor.source_map_enabled = false
  env = Opal::Environment.new
  env.append_path "."
  File.open("out/mt7.js", "w+") do |out|
    out << env["mt7"].to_s
  end
end
