// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.VBox vbox2;
    
    private Gtk.Frame frame1;
    
    private Gtk.Alignment GtkAlignment;
    
    private Gtk.VBox vbox4;
    
    private Gtk.CheckButton checkbutton2;
    
    private Gtk.FileChooserButton filechooserbutton1;
    
    private Gtk.Label GtkLabel2;
    
    private Gtk.Frame frame2;
    
    private Gtk.Alignment GtkAlignment1;
    
    private Gtk.VBox vbox3;
    
    private Gtk.Frame frame4;
    
    private Gtk.Alignment GtkAlignment3;
    
    private Gtk.FileChooserButton filechooserbutton2;
    
    private Gtk.Label GtkLabel6;
    
    private Gtk.CheckButton checkbutton1;
    
    private Gtk.Label GtkLabel5;
    
    private Gtk.Frame frame3;
    
    private Gtk.Alignment GtkAlignment2;
    
    private Gtk.HBox hbox1;
    
    private static Gtk.Button button2;
    
    private Gtk.VBox vbox1;
    
    private Gtk.VBox vbox5;
    
    private static Gtk.ProgressBar progressbar1;
    
    private static Gtk.Statusbar statusbar1;
    
    private Gtk.Label GtkLabel10;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("(ymt5gui) mt5 to objf");
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        this.BorderWidth = ((uint)(3));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.vbox2 = new Gtk.VBox();
        this.vbox2.Name = "vbox2";
        this.vbox2.Spacing = 6;
        // Container child vbox2.Gtk.Box+BoxChild
        this.frame1 = new Gtk.Frame();
        this.frame1.Name = "frame1";
        // Container child frame1.Gtk.Container+ContainerChild
        this.GtkAlignment = new Gtk.Alignment(0F, 0F, 1F, 1F);
        this.GtkAlignment.Name = "GtkAlignment";
        this.GtkAlignment.LeftPadding = ((uint)(12));
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        this.vbox4 = new Gtk.VBox();
        this.vbox4.Name = "vbox4";
        this.vbox4.Spacing = 6;
        // Container child vbox4.Gtk.Box+BoxChild
        this.checkbutton2 = new Gtk.CheckButton();
        this.checkbutton2.CanFocus = true;
        this.checkbutton2.Name = "checkbutton2";
        this.checkbutton2.Label = Mono.Unix.Catalog.GetString("extract all mt5 from directory");
        this.checkbutton2.DrawIndicator = true;
        this.checkbutton2.UseUnderline = true;
        this.vbox4.Add(this.checkbutton2);
        Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox4[this.checkbutton2]));
        w1.Position = 0;
        w1.Expand = false;
        w1.Fill = false;
        // Container child vbox4.Gtk.Box+BoxChild
        this.filechooserbutton1 = new Gtk.FileChooserButton(Mono.Unix.Catalog.GetString("Sélectionner un fichier"), ((Gtk.FileChooserAction)(0)));
        this.filechooserbutton1.Name = "filechooserbutton1";
        this.vbox4.Add(this.filechooserbutton1);
        Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox4[this.filechooserbutton1]));
        w2.Position = 1;
        w2.Expand = false;
        w2.Fill = false;
        this.GtkAlignment.Add(this.vbox4);
        this.frame1.Add(this.GtkAlignment);
        this.GtkLabel2 = new Gtk.Label();
        this.GtkLabel2.Name = "GtkLabel2";
        this.GtkLabel2.LabelProp = Mono.Unix.Catalog.GetString("<b>M</b>T5 path");
        this.GtkLabel2.UseMarkup = true;
        this.frame1.LabelWidget = this.GtkLabel2;
        this.vbox2.Add(this.frame1);
        Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.vbox2[this.frame1]));
        w5.Position = 0;
        w5.Expand = false;
        w5.Fill = false;
        // Container child vbox2.Gtk.Box+BoxChild
        this.frame2 = new Gtk.Frame();
        this.frame2.Name = "frame2";
        // Container child frame2.Gtk.Container+ContainerChild
        this.GtkAlignment1 = new Gtk.Alignment(0F, 0F, 1F, 1F);
        this.GtkAlignment1.Name = "GtkAlignment1";
        this.GtkAlignment1.LeftPadding = ((uint)(12));
        // Container child GtkAlignment1.Gtk.Container+ContainerChild
        this.vbox3 = new Gtk.VBox();
        this.vbox3.Name = "vbox3";
        this.vbox3.Spacing = 6;
        // Container child vbox3.Gtk.Box+BoxChild
        this.frame4 = new Gtk.Frame();
        this.frame4.Name = "frame4";
        this.frame4.ShadowType = ((Gtk.ShadowType)(0));
        // Container child frame4.Gtk.Container+ContainerChild
        this.GtkAlignment3 = new Gtk.Alignment(0F, 0F, 1F, 1F);
        this.GtkAlignment3.Name = "GtkAlignment3";
        this.GtkAlignment3.LeftPadding = ((uint)(12));
        // Container child GtkAlignment3.Gtk.Container+ContainerChild
        this.filechooserbutton2 = new Gtk.FileChooserButton(Mono.Unix.Catalog.GetString("Sélectionner un fichier"), ((Gtk.FileChooserAction)(2)));
        this.filechooserbutton2.Name = "filechooserbutton2";
        this.GtkAlignment3.Add(this.filechooserbutton2);
        this.frame4.Add(this.GtkAlignment3);
        this.GtkLabel6 = new Gtk.Label();
        this.GtkLabel6.Name = "GtkLabel6";
        this.GtkLabel6.LabelProp = Mono.Unix.Catalog.GetString("Output path to objf");
        this.GtkLabel6.UseMarkup = true;
        this.frame4.LabelWidget = this.GtkLabel6;
        this.vbox3.Add(this.frame4);
        Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.vbox3[this.frame4]));
        w8.Position = 0;
        w8.Expand = false;
        w8.Fill = false;
        // Container child vbox3.Gtk.Box+BoxChild
        this.checkbutton1 = new Gtk.CheckButton();
        this.checkbutton1.CanFocus = true;
        this.checkbutton1.Name = "checkbutton1";
        this.checkbutton1.Label = Mono.Unix.Catalog.GetString("do not use triangle strip (obj compatible)");
        this.checkbutton1.Active = true;
        this.checkbutton1.DrawIndicator = true;
        this.checkbutton1.UseUnderline = true;
        this.vbox3.Add(this.checkbutton1);
        Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.vbox3[this.checkbutton1]));
        w9.Position = 1;
        w9.Expand = false;
        w9.Fill = false;
        this.GtkAlignment1.Add(this.vbox3);
        this.frame2.Add(this.GtkAlignment1);
        this.GtkLabel5 = new Gtk.Label();
        this.GtkLabel5.Name = "GtkLabel5";
        this.GtkLabel5.LabelProp = Mono.Unix.Catalog.GetString("<b>O</b>bjf pathes");
        this.GtkLabel5.UseMarkup = true;
        this.frame2.LabelWidget = this.GtkLabel5;
        this.vbox2.Add(this.frame2);
        Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.vbox2[this.frame2]));
        w12.Position = 1;
        w12.Expand = false;
        w12.Fill = false;
        // Container child vbox2.Gtk.Box+BoxChild
        this.frame3 = new Gtk.Frame();
        this.frame3.Name = "frame3";
        // Container child frame3.Gtk.Container+ContainerChild
        this.GtkAlignment2 = new Gtk.Alignment(0F, 0F, 1F, 1F);
        this.GtkAlignment2.Name = "GtkAlignment2";
        this.GtkAlignment2.LeftPadding = ((uint)(12));
        // Container child GtkAlignment2.Gtk.Container+ContainerChild
        this.hbox1 = new Gtk.HBox();
        this.hbox1.Name = "hbox1";
        this.hbox1.Spacing = 6;
        // Container child hbox1.Gtk.Box+BoxChild
        button2 = new Gtk.Button();
        button2.CanFocus = true;
        button2.Name = "button2";
        button2.UseUnderline = true;
        button2.Label = Mono.Unix.Catalog.GetString("Generate");
        this.hbox1.Add(button2);
        Gtk.Box.BoxChild w13 = ((Gtk.Box.BoxChild)(this.hbox1[button2]));
        w13.Position = 0;
        w13.Expand = false;
        w13.Fill = false;
        // Container child hbox1.Gtk.Box+BoxChild
        this.vbox1 = new Gtk.VBox();
        this.vbox1.Name = "vbox1";
        this.vbox1.Spacing = 6;
        // Container child vbox1.Gtk.Box+BoxChild
        this.vbox5 = new Gtk.VBox();
        this.vbox5.Name = "vbox5";
        this.vbox5.Spacing = 6;
        // Container child vbox5.Gtk.Box+BoxChild
        progressbar1 = new Gtk.ProgressBar();
        progressbar1.Name = "progressbar1";
        this.vbox5.Add(progressbar1);
        Gtk.Box.BoxChild w14 = ((Gtk.Box.BoxChild)(vbox5[progressbar1]));
        w14.Position = 0;
        w14.Expand = false;
        w14.Fill = false;
        // Container child vbox5.Gtk.Box+BoxChild
        statusbar1 = new Gtk.Statusbar();
        statusbar1.Name = "statusbar1";
        statusbar1.Spacing = 6;
        this.vbox5.Add(statusbar1);
        Gtk.Box.BoxChild w15 = ((Gtk.Box.BoxChild)(this.vbox5[statusbar1]));
        w15.Position = 1;
        w15.Expand = false;
        w15.Fill = false;
        this.vbox1.Add(this.vbox5);
        Gtk.Box.BoxChild w16 = ((Gtk.Box.BoxChild)(this.vbox1[this.vbox5]));
        w16.Position = 0;
        w16.Expand = false;
        w16.Fill = false;
        this.hbox1.Add(this.vbox1);
        Gtk.Box.BoxChild w17 = ((Gtk.Box.BoxChild)(this.hbox1[this.vbox1]));
        w17.Position = 1;
        this.GtkAlignment2.Add(this.hbox1);
        this.frame3.Add(this.GtkAlignment2);
        this.GtkLabel10 = new Gtk.Label();
        this.GtkLabel10.Name = "GtkLabel10";
        this.GtkLabel10.LabelProp = Mono.Unix.Catalog.GetString("<b>M</b>t52objf");
        this.GtkLabel10.UseMarkup = true;
        this.frame3.LabelWidget = this.GtkLabel10;
        this.vbox2.Add(this.frame3);
        Gtk.Box.BoxChild w20 = ((Gtk.Box.BoxChild)(this.vbox2[this.frame3]));
        w20.Position = 2;
        w20.Expand = false;
        w20.Fill = false;
        this.Add(this.vbox2);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 764;
        this.DefaultHeight = 245;
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        this.checkbutton2.Toggled += new System.EventHandler(this.onMt5DirectoryToggle);
        button2.Clicked += new System.EventHandler(this.OnButton2Clicked);
    }
}
